/*
 * Copyright (C) 2017 taylor.fish <contact@taylor.fish>
 *
 * This file is part of Fish AmpMod.
 *
 * Fish AmpMod is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Fish AmpMod is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Fish AmpMod.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was automatically generated by generate_plugin_data.py.

#ifndef PORTS_H
#define PORTS_H

enum {
    PORT_INPUT_L = 0,
    PORT_OUTPUT_L = 1,
    PORT_INPUT_R = 2,
    PORT_OUTPUT_R = 3,
    PORT_EXPONENT = 4,
    PORT_BASE = 5,
    PORT_INCREMENT = 6,
    PORT_MIN_MULT = 7,
};

#endif
